### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by xKaelyn** [vDokkaebi/Natsuki-API#1]

**Comment by JuniorS6** [comment]
@vDokkaebi  I would like to work on this
Please assign this task to me.

**Comment by xKaelyn** [comment]
> @vDokkaebi I would like to work on this Please assign this task to me.

Do you even know what this project is going to be?

**Comment by JuniorS6** [comment]
No but I would love to work along

**Comment by xKaelyn** [comment]
> No but I would love to work along

Send me a DM on Discord.
`Dokkaebi#1064`

**Comment by JuniorS6** [comment]
> > No but I would love to work along
> 
> Send me a DM on Discord. `Dokkaebi#1064`

alright
